export { default as StartScreen } from './StartScreen/StartScreen'
export { default as LoginScreen } from './Login/LoginScreen'
export { default as RegisterScreen } from './RegisterScreen/RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPassword/ResetPasswordScreen'
export { default as Dashboard } from './Dashboard/Dashboard'
export {default as Logout} from './Logout/Logout'
export {default as ListHotelsScreen} from './tabs/ListHotelsScreen/ListHotelsScreen'
export {default as UserProfile} from './tabs/MenuScreen/UserProfile/UserProfile'
export {default as Policies} from './TermsandPolicies/Policies'
export {default as MainTabNavigator} from './tabs/MainTabNavigator'
